### ISSUE TITLE
oracle建表语句少了history表

### ISSUE THREAD

**Issue by playgod1984** [alenfive/rocket-api#23]
两条
CREATE TABLE "API_INFO"

**Comment by alenfive** [comment]
oracle 建表地址：
https://alenfive.gitbook.io/rocket-api/shu-ju-ku-chuang-jian-jiao-ben/oracle

**Comment by alenfive** [comment]
谢谢你的反馈 文档已修改：
见：https://alenfive.gitbook.io/rocket-api/shu-ju-ku-chuang-jian-jiao-ben/oracle
