### ISSUE TITLE
合理化建议

### ISSUE THREAD

**Issue by cmdares** [alenfive/rocket-api#39]
1、如果不是操作数据库，应用界面上默认数据库的选择界面实际没有意义，反而可能造成后端无故打卡数据连接。

2、如果一个API中需要访问多个不同的数据库，并将结果拼接输出情况，如何解决？
是否可考虑：在面板中增加一个开启数据连接的功能，提供[+]和[-]开启或关闭需要连接的数据库，通过开启数据数据库名称即为全局变量名称，可以在API中显示调用，清晰明了。

3、返回Json的统一模板能否开放，提供自定义json结构的命名。
比如：
当前系统返回的内容，如下
{
	"totalRecords": 1,
	"data": [
		{
			"name": "magic",
			"id": "5f9fb1b6f8b91c4a04a63a85",
			"sex": 1
		}
	],
	"pageNo": 1,
	"totalPages": 1,
	"pageSize": 1,
	"index": 0
}

我能否重命名 “totalRecords” 叫total，pageNo、totalPages、pageSize、index 修改名称，或者去掉一些返回值。

**Comment by alenfive** [comment]
你好，很高兴收到你提的建议
1. 根据排查，发现打开编辑页面时，执行了一次历史版本查询的数据库操作，所以打开了一次数据库连接，接下来会做界面上的优化，当只有需要历史版本回滚，或历史版本比对时才加载该信息，请持续关注

2.数据处理这一块使用groovy语法，详见：https://alenfive.gitbook.io/rocket-api/yu-fa-1/yu-fa

3. 返回结果可以实现自定义，详见：
自定义分页：https://alenfive.gitbook.io/rocket-api/zi-ding-yi-kuo-zhan/fen-ye-cha-xun
自定义返回结构：https://alenfive.gitbook.io/rocket-api/zi-ding-yi-kuo-zhan/zi-ding-yi-fan-hui-jie-gou-feng-zhuang

**Comment by cmdares** [comment]
感谢
