### ISSUE TITLE
希望支持ElasticSearch

### ISSUE THREAD

**Issue by cmdares** [alenfive/rocket-api#50]
如题，希望支持ElasticSearch数据源，以及封装数据访问的接口。
注意：支持ElasticSearch的几种认证模式的连接配置。

**Comment by alenfive** [comment]
1. 目前有提供接口来实现使用各种数据源的需求，查看：https://alenfive.gitbook.io/rocket-api/zi-ding-yi-kuo-zhan/zi-ding-yi-shu-ju-yuan
2.  elasticsearch 会在后面的迭代里考虑加入
