### ISSUE TITLE
repository 增加多层目录

### ISSUE THREAD

**Issue by cmdares** [alenfive/rocket-api#52]
当前目录仅为2层，希望能够进行创建多层目录。由于目前考虑设计系统多级模块，多级对象的CURD。两层管理不方便。
如果涉及到数百个API的情况。同时也可否考虑提供个API管理列表。提高管理的便捷性。

**Comment by alenfive** [comment]
1. 增加多级目录的需求，最近也有在考虑，是个好建议,我已经将他列入了接下来的迭代内容中
2. 你指的API管理列表是怎样的形式，repository 的区别是什么

**Comment by alenfive** [comment]
在最新版本中已支持目录的任意创建
