### ISSUE TITLE
能否整合Groovy语法提示插件，使得前端书写代码时候可以进行API提示

### ISSUE THREAD

**Issue by cmdares** [alenfive/rocket-api#53]

**Comment by alenfive** [comment]
groovy的完整的语法提示我也想要，不过在市面上未找到合适的语法插件，如果你发现有这样的插件，赶紧告诉我

**Comment by cmdares** [comment]
@alenfive 目前找了当下的语法编辑器，最靠谱的也就是这个了
codemirror  
您网上调研下基于这个组件的玩法。

**Comment by itxve** [comment]
想知道demo中的interface-ui是什么😄

**Comment by alenfive** [comment]
> 想知道demo中的interface-ui是什么😄

UI访问路径

**Comment by alenfive** [comment]
> 您

目前已经是codemirror了，不过需要自己解析groovy语法才能实现groovy的提示，目前这块没找到现成的，自己写太麻烦了

**Comment by itxve** [comment]
是这个 interface-ui 这个么,貌似找不到有关介绍

**Comment by cmdares** [comment]
@alenfive 
您看看人家是这么做的。http://140.143.210.90:9999/magic/web/index.html
magic-api 目测也不错。您可以研究下代码。
