### ISSUE TITLE
提供一些高级样例

### ISSUE THREAD

**Issue by cmdares** [alenfive/rocket-api#54]
1、提供批量导入/更新，for循环 addBatch
2、动态传参，多条件组合查询，SQL模板类似Mybatis动态能力 动态拼接AND OR 组合条件
3、定时器，创建/停止/修改/运行定时器任务
4、操作Redis、MQ(含Redis、MQ注册）
5、通过HttpClient访问外部服务，获取数据后在本系统中再次发布
5、能够发布WebSocket服务?

**Comment by alenfive** [comment]
1. websocket应用场景比较少，似乎没必要
2. 定时器这个就走远了，分布式环境下，定时任务应该抽象成单独的服务是否合理一些
3. 操作redis,mq 他们都是spring bean对象，看调用spring bean例子就好
4. 第5点不太明白
5. 案例地址：http://39.98.181.90:8081/interface-ui
6. github国内太慢，我在gitee上建立了仓库:https://gitee.com/alenfive/rocket-api
