### ISSUE TITLE
请问支持动态复杂SQL查询吗

### ISSUE THREAD

**Issue by liujunhuagithub** [alenfive/rocket-api#56]

**Comment by alenfive** [comment]
要多复杂，支持mybatis类似的if 判断动态SQL

**Comment by cmdares** [comment]
@alenfive 对，if动态判断，list 参数的动态绑定等。

**Comment by alenfive** [comment]
http://39.98.181.90:8081/interface-ui?id=5fe7686c5a006b369828e22d&page=editor
更多案例
