### ISSUE TITLE
是否可以支持JWT权限认证

### ISSUE THREAD

**Issue by entrence** [alenfive/rocket-api#61]
看您并未再文档中介绍关于权限方面的问题，由于目前大部分的场景下都需要使用一种鉴权方式，JWT或者shrio都行，想问一下是否支持

**Comment by alenfive** [comment]
1. 鉴权的实现方式，应该在拦截器里体现：（通过对原springboot拦截器的封装，能够获得更多信息）https://alenfive.gitbook.io/rocket-api/zi-ding-yi-kuo-zhan/lan-jie-qi
2. 通过rocket-api建立的api，底层实现与springboot mapping注册方式一致，所以并不会影响到springboot依赖其他组件，他们是兼容的。所以jwt也好，shiro也好，auth2也好，都可以集成
3. github国内访问不太稳定，所以代码更新得不是很及时，我在gitee上建有了仓库：https://gitee.com/alenfive/rocket-api
