### ISSUE TITLE
分页查询在SQLserver 2008 R2 上使用关键字OFFSET，NEXT报错

### ISSUE THREAD

**Issue by zxavier94** [alenfive/rocket-api#63]
{"timestamp":"2021-07-16 10:36:40","status":500,"error":"Internal Server Error","message":"PreparedStatementCallback; uncategorized SQLException for SQL [select id,api_info_id,url,method,request_header,request_body,response_header,response_body,status,elapsed_time,editor,options,create_time from api_example where api_info_id=? order by id desc  OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY]; SQL state [S0001]; error code [102]; 'OFFSET' 附近有语法错误。; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: 'OFFSET' 附近有语法错误。","path":"/hkApp/api-example/last"}

**Comment by zxavier94** [comment]
com.github.alenfive.rocketapi.datasource.SQLServerDataSource#buildPageScript
![image](https://user-images.githubusercontent.com/19486599/125886553-b2ee4a20-7eec-4566-a0d0-05a894a42ac2.png)
这种分页方式不适合SQLserver 2008 r2版本

**Comment by zxavier94** [comment]
![image](https://user-images.githubusercontent.com/19486599/125894979-a84a4e2f-1e41-4bad-8b1e-2de0c23f1aee.png)
我先暂时这样修改源码
`       
 String sql = new StringBuilder("select * from (select ROW_NUMBER() OVER( order by id desc ) AS RowNumber, ")
                .append(String.join(",", FieldUtils.allTableFields(apiObject.getClass())))
                .append(" from ")
                .append(tableName)
                .append(where == null ? "" : " where " + where)
                .append(") as b where b.RowNumber BETWEEN ")
                .append((page.getPageNo() - 1)*page.getPageSize() + 1)
                .append(" and ")
                .append(page.getPageNo() * page.getPageSize())
                .toString();
`
com.github.alenfive.rocketapi.utils.ApiJpaUtil#pageByEntity 修改的这个方法

**Comment by alenfive** [comment]
1. sqlserver2008版本并没有实现
2. 已经提供了可扩展的方式，你可以参考`com.github.alenfive.rocketapi.datasource.SQLServerDataSource` 2012版本，
创建一个sqlserver2008版本的数据源。其中提供了自动分页的方法，覆盖重写即可。
![image](https://user-images.githubusercontent.com/9295325/126752040-306bc882-1af2-44c4-af68-e6c12de4ab58.png)
3.有市面上其他类型的数据源，也按照这样的方式扩展
4.如果你有完成2008版本的代码，可以提交合并给我，期待收到你的代码
