### ISSUE TITLE
我整合到我的项目里了之后，用生成的api访问出错

### ISSUE THREAD

**Issue by ly886** [alenfive/rocket-api#65]
会出现404访问问题，请问我需要做些什么。。
BODY
{
    "timestamp": 1634284270660,
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/interface-ui/interface-ui/at"
}

**Comment by alenfive** [comment]
1. /interface-ui/interface-ui/at 这是什么访问路径啊,不会有这样的路径的
2. 我迁移到了gitee中，有问题在那里再留言给我https://gitee.com/alenfive/rocket-api
